# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.13.0"
    displayName: "Install Node.js"

  - script: |
      npm install -g mbt
      npm config set "@sap:registry" "https://npm.sap.com"

  - script: |
      npm install
      mbt build
    displayName: "npm install"


  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: |
        mta_archives/**
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    displayName: "Publish Artifact"
